import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch } from "react-redux";
import { getSampleRequestedAction } from "@/lib/ducks/sample/actions";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function OtherHome() {
  const dispatch = useDispatch();
  const router = useRouter();
  const onClick = () => {
    dispatch(getSampleRequestedAction({ value: true }));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2 className={inter.className}>Other Home Page</h2>
        <button onClick={onClick}>Click me</button>
      </main>
    </>
  );
}
